import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/Footer'
import CountdownTimer from '../components/navbar/countdown/countdownTimer'
import Navbar from '../components/navbar/Navbar'
import styles from '../styles/Home.module.css'
import Category from '../components/category'
import Campaigns from '../components/camp/campaigns/Campaigns'
import Gallery from '../components/Gallery'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Shein</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Category />
      <Campaigns />
      <Gallery />
    </div>
  )

}
